package fr.nicolaslinard.po.toolbox.models

/**
 * A white-key note (A-G). The PO-14 Sub only stores natural notes; sharps
 * are produced live via the "half note up" effect — see [PO14Step].
 */
enum class Pitch(val letter: String, val semitonesFromC: Int) {
    C("C", 0), D("D", 2), E("E", 4), F("F", 5), G("G", 7), A("A", 9), B("B", 11);

    companion object {
        fun fromLetter(letter: String): Pitch? =
            entries.find { it.letter.equals(letter, ignoreCase = true) }
    }
}

/**
 * One programmed note on the PO-14 Sub sequencer.
 * @param halfToneUp whether effect 15 ("half note up") is triggered live on
 *   this step, raising the note a semitone to reach a black key. On the
 *   real device this is a timing-sensitive live performance action, not a
 *   value you can just dial in with knob A — see the programming
 *   instructions generated by [fr.nicolaslinard.po.toolbox.io.MarkdownWriter].
 */
data class PO14Step(
    val pitch: Pitch,
    val octave: Int = 3,
    val halfToneUp: Boolean = false
) {
    init {
        require(octave in 0..8) { "Octave must be between 0 and 8" }
    }

    /** MIDI note number (C4 = 60), honouring the half-tone-up effect. */
    val midiNote: Int get() = (octave + 1) * 12 + pitch.semitonesFromC + if (halfToneUp) 1 else 0

    /** Compact text form used in markdown files and the UI, e.g. "D#3" or "C4". */
    val noteText: String get() = "${pitch.letter}${if (halfToneUp) "#" else ""}$octave"
}

/**
 * Represents a pattern for the Pocket Operator PO-14 (Sub).
 * Unlike the PO-12's per-voice boolean grid, the PO-14 is monophonic: one
 * bass sound plays across the 16 steps, and each step carries at most one
 * note (or is a rest).
 */
data class PO14Pattern(
    val steps: Map<Int, PO14Step>, // step (1-16) -> note; absent = rest
    val sound: POVoice,
    override val metadata: PatternMetadata,
    override val number: Int = 1
) : AnyPattern {
    init {
        require(number in 1..16) { "Pattern number must be between 1 and 16" }
        require(steps.keys.all { it in 1..16 }) { "All steps must be between 1 and 16" }
    }

    fun getNote(step: Int): PO14Step? = steps[step]
}
